# players (x, y, hp, weapon, item, armour, turn)
# items (rarity, name, description, effect, modifier)
# armour (name, modifier)
# monsters (name, hp, damage)
# rooms (x, y, monsters, items)
# weapons (rarity, name, description, damage)